//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.20.0.3
//     Timestamp      : 2024/9/7 10:51:20
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace DynamicMenus

    Public Partial Class frmMenuBuilder

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private grpInstructions As System.Windows.Forms.GroupBox
        Private label1 As System.Windows.Forms.Label
        Private label2 As System.Windows.Forms.Label
        Private label3 As System.Windows.Forms.Label
        Private textBox1 As System.Windows.Forms.TextBox
        Private textBox2 As System.Windows.Forms.TextBox
        Private listItems As System.Windows.Forms.ListBox
        Private cmdAdd As System.Windows.Forms.Button
        Private cmdRemove As System.Windows.Forms.Button
        Private cmdRefresh As System.Windows.Forms.Button
        Private cmdClose As System.Windows.Forms.Button

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void Strict

            If (disposing .and. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated Code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                                                                                                                                                                                                Private Method InitializeComponent() As Void Strict
            Self:grpInstructions := System.Windows.Forms.GroupBox{}
            Self:label1 := System.Windows.Forms.Label{}
            Self:label2 := System.Windows.Forms.Label{}
            Self:label3 := System.Windows.Forms.Label{}
            Self:textBox1 := System.Windows.Forms.TextBox{}
            Self:textBox2 := System.Windows.Forms.TextBox{}
            Self:listItems := System.Windows.Forms.ListBox{}
            Self:cmdAdd := System.Windows.Forms.Button{}
            Self:cmdRemove := System.Windows.Forms.Button{}
            Self:cmdRefresh := System.Windows.Forms.Button{}
            Self:cmdClose := System.Windows.Forms.Button{}
            Self:grpInstructions:SuspendLayout()
            Self:SuspendLayout()
            // 
            // grpInstructions
            // 
            Self:grpInstructions:Controls:Add(Self:label1)
            Self:grpInstructions:Location := System.Drawing.Point{43, 42}
            Self:grpInstructions:Name := "grpInstructions"
            Self:grpInstructions:Size := System.Drawing.Size{765, 100}
            Self:grpInstructions:TabIndex := 0
            Self:grpInstructions:TabStop := false
            Self:grpInstructions:Text := "Instructions"
            // 
            // label1
            // 
            Self:label1:Location := System.Drawing.Point{17, 28}
            Self:label1:Name := "label1"
            Self:label1:Size := System.Drawing.Size{729, 62}
            Self:label1:TabIndex := 0
            Self:label1:Text := "Type the text of the menu item in the Prompt text box and click Add to add the menu item to the list.  Click Refresh to update the menu with the list of menu items."
            // 
            // label2
            // 
            Self:label2:AutoSize := true
            Self:label2:Location := System.Drawing.Point{63, 194}
            Self:label2:Name := "label2"
            Self:label2:Size := System.Drawing.Size{62, 18}
            Self:label2:TabIndex := 1
            Self:label2:Text := "Prompt"
            // 
            // label3
            // 
            Self:label3:AutoSize := true
            Self:label3:Location := System.Drawing.Point{63, 236}
            Self:label3:Name := "label3"
            Self:label3:Size := System.Drawing.Size{71, 18}
            Self:label3:TabIndex := 2
            Self:label3:Text := "Message"
            // 
            // textBox1
            // 
            Self:textBox1:Location := System.Drawing.Point{188, 189}
            Self:textBox1:Name := "textBox1"
            Self:textBox1:Size := System.Drawing.Size{429, 28}
            Self:textBox1:TabIndex := 3
            // 
            // textBox2
            // 
            Self:textBox2:Location := System.Drawing.Point{188, 231}
            Self:textBox2:Name := "textBox2"
            Self:textBox2:Size := System.Drawing.Size{429, 28}
            Self:textBox2:TabIndex := 4
            // 
            // listItems
            // 
            Self:listItems:FormattingEnabled := true
            Self:listItems:ItemHeight := 18
            Self:listItems:Location := System.Drawing.Point{188, 294}
            Self:listItems:Name := "listItems"
            Self:listItems:Size := System.Drawing.Size{429, 238}
            Self:listItems:TabIndex := 5
            // 
            // cmdAdd
            // 
            Self:cmdAdd:Location := System.Drawing.Point{680, 300}
            Self:cmdAdd:Name := "cmdAdd"
            Self:cmdAdd:Size := System.Drawing.Size{134, 37}
            Self:cmdAdd:TabIndex := 6
            Self:cmdAdd:Text := "&Add"
            Self:cmdAdd:UseVisualStyleBackColor := true
            // 
            // cmdRemove
            // 
            Self:cmdRemove:Location := System.Drawing.Point{680, 364}
            Self:cmdRemove:Name := "cmdRemove"
            Self:cmdRemove:Size := System.Drawing.Size{134, 37}
            Self:cmdRemove:TabIndex := 7
            Self:cmdRemove:Text := "Remo&ve"
            Self:cmdRemove:UseVisualStyleBackColor := true
            // 
            // cmdRefresh
            // 
            Self:cmdRefresh:Location := System.Drawing.Point{680, 428}
            Self:cmdRefresh:Name := "cmdRefresh"
            Self:cmdRefresh:Size := System.Drawing.Size{134, 37}
            Self:cmdRefresh:TabIndex := 8
            Self:cmdRefresh:Text := "&Remove"
            Self:cmdRefresh:UseVisualStyleBackColor := true
            // 
            // cmdClose
            // 
            Self:cmdClose:Location := System.Drawing.Point{680, 492}
            Self:cmdClose:Name := "cmdClose"
            Self:cmdClose:Size := System.Drawing.Size{134, 37}
            Self:cmdClose:TabIndex := 9
            Self:cmdClose:Text := "&Close"
            Self:cmdClose:UseVisualStyleBackColor := true
            // 
            // frmMenuBuilder
            // 
            Self:AutoScaleDimensions := System.Drawing.SizeF{9, 18}
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:ClientSize := System.Drawing.Size{858, 568}
            Self:Controls:Add(Self:cmdClose)
            Self:Controls:Add(Self:cmdRefresh)
            Self:Controls:Add(Self:cmdRemove)
            Self:Controls:Add(Self:cmdAdd)
            Self:Controls:Add(Self:listItems)
            Self:Controls:Add(Self:textBox2)
            Self:Controls:Add(Self:textBox1)
            Self:Controls:Add(Self:label3)
            Self:Controls:Add(Self:label2)
            Self:Controls:Add(Self:grpInstructions)
            Self:Name := "frmMenuBuilder"
            Self:StartPosition := System.Windows.Forms.FormStartPosition.CenterScreen
            Self:Text := "Add Menu Items at Runtime"
            Self:grpInstructions:ResumeLayout(false)
            Self:ResumeLayout(false)
            Self:PerformLayout()
        End Method
        #endregion
    End Class 
End Namespace
